---
- name: Check if helm is installed
  command: which helm
  register: helm_installed_output
  changed_when: false
  failed_when: false

- name: Install helm
  shell: curl -L https://git.io/get_helm.sh | bash
  args:
    warn: false
  when: "'helm' not in helm_installed_output.stdout"

- name: Copy tiller-serviceaccount.yml to /tmp
  copy:
    src: tiller-serviceaccount.yml
    dest: /tmp/tiller-serviceaccount.yml

- name: Create tiller service account
  command: kubectl apply -f /tmp/tiller-serviceaccount.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Initialize tiller
  command: >
    helm init
    --service-account tiller
    --history-max 10
    --node-selectors kubernetes.io/hostname=master
    --override spec.template.spec.tolerations[0].key=node-role.kubernetes.io/master
    --override spec.template.spec.tolerations[0].operator=Exists
    --override spec.template.spec.tolerations[0].effect=NoSchedule
    --wait
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Initialize user helm client
  command: helm init --client-only
  become: true
  become_user: '{{ ansible_user }}'

- name: Helm install nfs client
  command: helm install --set nfs.server={{ private_network_ip }} --set nfs.path=/var/nfs/kubernetes stable/nfs-client-provisioner
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf