---
- name: Check if helm is installed
  command: which helm
  register: helm_installed_output
  changed_when: false
  failed_when: false

- name: Install helm
  shell: curl -L https://git.io/get_helm.sh | bash
  args:
    warn: false
  when: "'helm' not in helm_installed_output.stdout"

- name: Copy tiller-serviceaccount.yml to /tmp
  copy:
    src: tiller-serviceaccount.yml
    dest: /tmp/tiller-serviceaccount.yml

- name: Create tiller service account
  command: kubectl apply -f /tmp/tiller-serviceaccount.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Initialize tiller
  command: helm init  --tiller-namespace kube-system --service-account tiller --history-max 10
  become: true
  become_user: '{{ ansible_user }}'