---
- hosts: master
  become: true
  roles:
    - geerlingguy.swap
    - nfs-server
    - docker
    - kubebin
    - master-config
    - helm
    - nfs-client
    - ingress-controller
    - dns-server
    - dns-client