---
- hosts: master
  become: true
  roles:
    - geerlingguy.swap
    - dns-server
    - dns-client
    - nfs-server
    - master-config
    - helm
    - nfs-client
    - ingress-controller
    - load-balancer
