---
- name: Setup kubelet extra args
  template:
    src: kubelet-extra-args.j2
    dest: /etc/default/kubelet

- name: Check if kubelet is running
  shell: ps -e | grep kubelet
  register: kubelet_pid_output
  changed_when: false
  failed_when: false

- name: Join node with master
  command: "{{ hostvars['master']['kubeadm_join_command'] }}"
  when: "'kubelet' not in kubelet_pid_output.stdout"