---
- name: Helm install metallb load balancer
  command: >
    helm upgrade
    --install
    --namespace metallb-system
    --set controller.nodeSelector."kubernetes\.io/hostname"=master
    --set controller.tolerations[0].key=node-role.kubernetes.io/master
    --set controller.tolerations[0].operator=Exists
    --set controller.tolerations[0].effect=NoSchedule
    --set speaker.tolerations[0].key=node-role.kubernetes.io/master
    --set speaker.tolerations[0].operator=Exists
    --set speaker.tolerations[0].effect=NoSchedule
    metallb
    stable/metallb
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Setup metallb configmap file
  template:
    src: metallb-config.j2
    dest: /tmp/metallb-config.yml

- name: Create metallb configmap
  command: kubectl apply -f /tmp/metallb-config.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
